name: Lint Code with Prettier
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node --version
      - run: npm --version
      - run: yarn
      - run: yarn lint
